## 1.5 线性代数

In [1]:
import numpy as np

x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])

print(x)
print(y)
print(x.dot(y)) # 矩阵点乘

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
[[ 28.  64.]
 [ 67. 181.]]


In [2]:
print(np.dot(x, y)) # 等价

[[ 28.  64.]
 [ 67. 181.]]


In [3]:
print(np.ones(3))
print(np.dot(x, np.ones(3)))

[1. 1. 1.]
[ 6. 15.]


In [4]:
print(x @ np.ones(3)) # @符（类似Python 3.5）也可以用作中缀运算符，进行矩阵乘法

[ 6. 15.]


numpy.linalg中有一组标准的矩阵分解运算以及诸如求逆和行列式之类的东西。它们跟MATLAB和R等语言所使用的是相同的行业标准线性代数库，如BLAS、LAPACK、Intel MKL（Math Kernel Library，可能有，取决于你的NumPy版本）等：

In [5]:
from numpy.linalg import inv, qr

X = np.random.randn(5,5)
mat = X.T.dot(X)
print(mat.dot(inv(mat)))

[[ 1.00000000e+00  6.96420625e-16  3.47018808e-15 -1.01006895e-16
  -2.17186096e-15]
 [-8.79062497e-16  1.00000000e+00  1.49861363e-15  1.29757991e-15
  -5.53236570e-15]
 [-9.37633993e-16  6.40611471e-15  1.00000000e+00  1.09180238e-15
   4.00023759e-15]
 [ 1.00236180e-15 -1.65748770e-16  3.96550551e-15  1.00000000e+00
   2.97141811e-15]
 [-3.99394956e-15  5.78205988e-15 -3.44535672e-14  1.51157079e-15
   1.00000000e+00]]


In [6]:
q, r = qr(mat)
print(r)

[[-4.58616461 -3.20608481  3.28901761  3.976992   -4.34332505]
 [ 0.         -6.80533329 -0.84172692  2.6348389  -0.29030822]
 [ 0.          0.         -4.12952901  0.17187343  5.48481964]
 [ 0.          0.          0.         -2.16182571 -0.134159  ]
 [ 0.          0.          0.          0.          0.01709002]]


## 1.6 伪随机数生成

numpy.random模块对Python内置的random进行了补充，增加了一些用于高效生成多种概率分布的样本值的函数。例如，你可以用normal来得到一个标准正态分布的4×4样本数组：

In [7]:
samples = np.random.normal(size=(4,4))
print(samples)

[[-0.14504577  0.25359445 -0.0091253   0.86094021]
 [ 0.03314763  0.1948643  -2.18139433  0.416864  ]
 [-1.08478051 -0.50364658  1.87897998  0.21095218]
 [ 1.14248601  0.59205406  1.03364924  1.37001225]]


而Python内置的random模块则只能一次生成一个样本值。从下面的测试结果中可以看出，如果需要产生大量样本值，numpy.random快了不止一个数量级：

In [8]:
from random import normalvariate

N = 1000000
%timeit samples = [normalvariate(0,1) for _ in range(N)]
%timeit np.random.normal(size=N)

671 ms ± 3.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
29.8 ms ± 567 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


我们说这些都是伪随机数，是因为它们都是通过算法基于随机数生成器种子，在确定性的条件下生成的。你可以用NumPy的np.random.seed更改随机数生成种子：

In [9]:
np.random.seed(1234)

numpy.random的数据生成函数使用了全局的随机种子。要避免全局状态，你可以使用numpy.random.RandomState，创建一个与其它隔离的随机数生成器：

In [10]:
rng = np.random.RandomState(1234)
print(rng.randn(10))

[ 0.47143516 -1.19097569  1.43270697 -0.3126519  -0.72058873  0.88716294
  0.85958841 -0.6365235   0.01569637 -2.24268495]
