## 1.1.5 基本的索引和切片

In [2]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(arr[5])

5


In [4]:
print(arr[5:8])

[5 6 7]


In [5]:
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [6]:
arr_slice = arr[5:8]
print(arr_slice)

[12 12 12]


In [7]:
arr_slice[1] = 12345
print(arr)

[    0     1     2     3     4    12 12345    12     8     9]


In [8]:
arr_slice[:] = 64
print(arr)

[ 0  1  2  3  4 64 64 64  8  9]


数据不会被复制，视图上的任何修改都会直接反映到源数组上。

如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如arr[5:8].copy()

In [9]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])

[7 8 9]


In [11]:
# 递归访问
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [12]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


In [14]:
# 将arr3d[0]的数据进行备份
old_values = arr3d[0].copy()
# 修改arr3d[0]的值为42
arr3d[0] = 42
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
arr3d[0] = old_values
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 1.1.6 切片索引

In [16]:
print(arr)
print(arr[1:6])

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64]


In [17]:
print(arr2d)
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [27]:
print(arr2d[:2,1:])

[[2 3]
 [5 6]]


In [28]:
print(arr2d[1,:2])

[4 5]


In [29]:
print(arr2d[:2, 2])

[3 6]


In [30]:
print(arr2d[:,:1])

[[1]
 [4]
 [7]]


## 1.1.7 布尔型索引

In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4) # 生成一些正态分布的随机数据
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-7.40039216e-01  3.96505966e-02  4.31983139e-01 -6.39978541e-01]
 [-1.07726145e+00 -8.20841582e-01 -1.17219803e+00 -7.91043225e-01]
 [ 9.47230158e-02  2.30688628e-01 -1.56695749e-01  4.68189737e-01]
 [-9.14650550e-01 -2.32421057e-01 -2.29350698e-03 -5.14709009e-01]
 [ 1.70553086e-01 -7.64114182e-01  9.75471755e-01 -3.00639356e-01]
 [-1.05022659e+00  3.92045947e-01  5.97237869e-01 -2.34732768e+00]
 [ 8.27323738e-01  8.52875724e-01  3.64818511e-01 -1.42289997e+00]]


In [33]:
print(names == 'Bob')

[ True False False  True False False False]


In [34]:
print(data[names == 'Bob'])

[[-0.74003922  0.0396506   0.43198314 -0.63997854]
 [-0.91465055 -0.23242106 -0.00229351 -0.51470901]]


In [35]:
print(data[names == 'Bob', 2:])
print('===========分割线============')
print(data[names == 'Bob', 3])

[[ 0.43198314 -0.63997854]
 [-0.00229351 -0.51470901]]
===========分割线============
[-0.63997854 -0.51470901]


In [36]:
print(names != 'Bob')
print(data[~(names == 'Bob')]) # 既可以使用不等于符号（!=），也可以通过~对条件进行否定

[False  True  True False  True  True  True]
[[-1.07726145 -0.82084158 -1.17219803 -0.79104323]
 [ 0.09472302  0.23068863 -0.15669575  0.46818974]
 [ 0.17055309 -0.76411418  0.97547175 -0.30063936]
 [-1.05022659  0.39204595  0.59723787 -2.34732768]
 [ 0.82732374  0.85287572  0.36481851 -1.42289997]]


In [37]:
cond = names == 'Bob'
print(data[~cond])

[[-1.07726145 -0.82084158 -1.17219803 -0.79104323]
 [ 0.09472302  0.23068863 -0.15669575  0.46818974]
 [ 0.17055309 -0.76411418  0.97547175 -0.30063936]
 [-1.05022659  0.39204595  0.59723787 -2.34732768]
 [ 0.82732374  0.85287572  0.36481851 -1.42289997]]


In [38]:
mask = (names == 'Bob') | (names == 'Will') # 布尔数组中and or无效，用& |
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[-0.74003922  0.0396506   0.43198314 -0.63997854]
 [ 0.09472302  0.23068863 -0.15669575  0.46818974]
 [-0.91465055 -0.23242106 -0.00229351 -0.51470901]
 [ 0.17055309 -0.76411418  0.97547175 -0.30063936]]


In [39]:
data[data < 0] = 0
print(data)

[[0.         0.0396506  0.43198314 0.        ]
 [0.         0.         0.         0.        ]
 [0.09472302 0.23068863 0.         0.46818974]
 [0.         0.         0.         0.        ]
 [0.17055309 0.         0.97547175 0.        ]
 [0.         0.39204595 0.59723787 0.        ]
 [0.82732374 0.85287572 0.36481851 0.        ]]


In [40]:
data[names != 'Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.         0.         0.         0.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.39204595 0.59723787 0.        ]
 [0.82732374 0.85287572 0.36481851 0.        ]]


## 1.1.8 花式索引

花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引

In [41]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [42]:
print(arr[[4,3,0,6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [43]:
print(arr[[-3,-5,-7]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [44]:
arr = np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7,2],[0,3,1,2]]) #二维检索 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [47]:
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


**花式索引跟切片不一样，总是将数据复制到新数组中**

---
## 1.1.9 数组转置和轴对换

In [48]:
arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.T) # T属性代表转置

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [49]:
arr = np.random.randn(6,3)
print(arr)
print(np.dot(arr.T, arr)) # 矩阵点乘

[[-0.96536657 -0.4809932  -0.67770851]
 [-0.69074037 -0.51353516  1.59178596]
 [ 0.08483264  0.55728683  0.19500756]
 [ 1.7229888  -1.12752948 -0.31181914]
 [-1.52061818  0.51368904  0.0500261 ]
 [-0.67134254 -0.75658612 -0.4515253 ]]
[[ 7.14792231 -1.34958677 -0.73893401]
 [-1.34958677  2.91326315  0.33611118]
 [-0.73893401  0.33611118  3.33470819]]


In [50]:
arr = np.arange(16).reshape((2,2,4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [51]:
# 对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [52]:
# ndarray还有一个swapaxes方法，它需要接受一对轴编号
print(arr)
print('=================')
print(arr.swapaxes(1,2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
